# FGDW002 - Fibaro Door Window Sensor 2
# https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/604
# https://www.opensmarthouse.org/zwavedatabase/604
-   deviceName: FGDW002 - Fibaro Door Window Sensor 2
    manufacturerId: 271 # 0x010F
    productTypeId: 1794 # 0702
    groups:
    # send alarm
        1: 1
    config: 
        # bitmask:
        # 2_1 Visual LED indications - Open/close = 1; 
        # 2_2 Visual LED indications - wake up = 0;
        # 2_4 Visual LED indications - tampering = 0
        # -> 2 = 1
        2_1: 1
        # Interval of temperature measurements
        50_2: 0
        # Temperature reports threshold
        51_2: 0
    wakeup: 64800 # 18 hours

# Fibargroup FGK101 Door Opening Sensor Version > 3.2
# https://www.opensmarthouse.org/zwavedatabase/381
-   deviceName: FGK101 - Fibaro Door Window Sensor 1.5
    manufacturerId: 271 # 0x010F
    productTypeId: 1793 # 0x0701
    groups:
    # send alarm
        1: 1
    config: 
        # bitmask:
        # 2_1 Visual LED indications - Open/close = 1; 
        # 2_2 Visual LED indications - wake up = 0;
        # 2_4 Visual LED indications - tampering = 0
        # -> 2 = 1
        2_1: 1
        # Interval of temperature measurements
        50_2: 0
        # Temperature reports threshold
        51_2: 0
    wakeup: 64800 # 18 hours

# Fibargroup FGK101 Door Opening Sensor Version <= 2.5
# https://www.opensmarthouse.org/zwavedatabase/125
# https://www.opensmarthouse.org/zwavedatabase/847
-   deviceName: FGK101 - Fibaro Door Window Sensor 1
    manufacturerId: 271 # 0x010F
    productTypeId: 1792 # 0x700
    groups:
    # send basic
        1: 1
    config: 
        # Status change signalled by LED
        # Default setting: 1
        # Available parameter settings:
        # 0 - LED turned Off,
        # 1 - LED turned On
        # Parameter value: 1 [byte].
        # -> 2 = 1
        2_1: 1
    wakeup: 64800 # 18 hours

# ZW100 Multisensor 6 1.12
# https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/778
# https://www.opensmarthouse.org/zwavedatabase/778
-   deviceName: ZW100 Multisensor 6
    manufacturerId: 134 # 0x0086
    productTypeId: 2
    productId: 100
    groups:
        1: 1
    config:
        # factory reset
        #255_4: 1431655765
        # Motion Sensor reset timeout
        3_2: 25
        # Motion sensor sensitivity, useful for some older devices
        4_1: 5 # 5: max sensitivity, default but some devices always reset to 0
        # Motion Sensor Triggered Command
        5_1: 2
        # sum of:
        # Battery=1
        # Ultraviolet=16
        # Temperature=32
        # Humidity=64
        # Light=128
        101_4: 97
        # Group 1 Report Interval
        # 111_4: 3600
    wakeup: 3600

# ZW100 Multisensor 6 1.12 battery profile
# https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/778
# https://www.opensmarthouse.org/zwavedatabase/778
-   deviceName: ZW100 Multisensor 6 battery powered
    manufacturerId: 134 # 0x0086
    productTypeId: 2
    productId: 100
    profile: battery
    groups:
        1: 1
    config:
        # factory reset
        #255_4: 1431655765
        # Motion Sensor reset timeout
        3_2: 25
        # Motion sensor sensitivity, useful for some older devices
        4_1: 5 # 5: max sensitivity, default but some devices always reset to 0
        # Motion Sensor Triggered Command
        5_1: 2
        # sum of:
        # Battery=1
        # Ultraviolet=16
        # Temperature=32
        # Humidity=64
        # Light=128
        101_4: 1 # only battery if battery powered
        # Group 1 Report Interval
        # 111_4: 3600
    wakeup: 3600

# FGWP102 Metered Wall Plug Switch
# https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/513
-   deviceName: FGWP102 Metered Wall Plug Switch
    manufacturerId: 271 # (0x10F)
    productTypeId: 1538 # (0x602)
    groups:
        1: 1
        #2: 1
        #3: 1
    config:
        # high priority power report threshold in percent (default is 80)
        10_1: 90
        # Standard power report threshold in percent (default is 15, 100 means disabled)
        11_1: 100
        # Power and energy periodic reports (default 3600s, 0 is inactive)
        14_2: 0

# FGWP101 Metered Wall Plug Switch
# https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/130
# https://www.opensmarthouse.org/zwavedatabase/130
-   deviceName: FGWP101 Metered Wall Plug Switch
    manufacturerId: 271 # (0x10F)
    productTypeId: 1536 # (0x600)
    groups:
        # 1: is assigned to Plugs status - On / Off. Allows for sending control command to associated devices whenever the Plug is turned On or Off.
        #1: 1
        #2: 1
        # 3: reports  relay's  status  to  just  one  device,  Z-Wave network's main controller by default. It's not recommended to modify settings of this association group.
        3: 1
    config:
        # Immediate power report
        40_1: 90
        # Standard power load reporting (default is 15, 100 means off)
        42_1: 100
        #  Time  period  between  reports  on  power  load  and  energy  consumption (default 3600s, 65535 to disable)
        47_2: 65535

# FGBS001 Universal Binary Sensor
# https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/126
-   deviceName: FGBS001 Universal Binary Sensor
    manufacturerId: 271
    productTypeId: 1281
    groups:
        1: 1
        2: 1
        3: 1
        
# FGBS222 Smart Implant
# https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/1005
# https://www.opensmarthouse.org/zwavedatabase/1005
-   deviceName: FGBS222 Smart Implant
    manufacturerId: 271
    productTypeId: 1282
    groups:
        1: 1
        2: 1
        3: 1
    config:
        20_1: 0
        21_1: 0

# ZW139 Nano Switch Gen5 (without meter)
# https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/648
# https://www.opensmarthouse.org/zwavedatabase/648
-   deviceName: ZW139 Nano Switch Gen5 (without meter)
    manufacturerId: 134
    productTypeId: 3
    productId: 139 #(0x008B)
    groups:
        1: 1
        3: 1
    config:
        80_1: 2
        120_1: 0
        121_1: 0

# AEON Labs ZW116 Aeotec Nano Switch
# https://www.opensmarthouse.org/zwavedatabase/591
-   deviceName: AEON Labs ZW116 Aeotec Nano Switch
    manufacturerId: 134
    productTypeId: 3
    productId: 116 #(0x74)
    groups:
        1: 1
        3: 1
    config:
        80_1: 2
        120_1: 0
        121_1: 0

# AEON Labs ZW096 Smart Switch 6
# https://www.opensmarthouse.org/zwavedatabase/63
-   deviceName: AEON Labs ZW096 Smart Switch 6
    manufacturerId: 134 # 0x0086
    productTypeId: 3 # 0x0003
    productId: 96 # 0x0060
    groups:
        1: 1
    config:
        # Configure the output load status after re-power on (0=last status, 1=always on, 2=always off)
        20_1: 1
        # Configure the state of LED. 0= The LED will follow the status (on/off) of its load (Energy mode). 1= When the state of Switch’s load changed, The LED will follow the status (on/off) of its load, but the red LED will turn off after 5 seconds if there is no any switch action (momentary indicate mode). 2= Night light mode.
        81_1: 1
        # Enables/disables parameter 91 and 92 below (1=enabled, 0=disabled).
        90_1: 1
        # The value here represents minimum change in wattage (in terms of wattage) for a REPORT to be sent (Valid values 0-60000).
        91_2: 15
        # The value here represents minimum change in wattage percent (in terms of percentage) for a REPORT to be sent (Valid values 0-100).
        92_1: 90
        # Which reports need to send in Report group 1
        101_4: 0
        # Which reports need to send in Report group 2
        102_4: 0
        # Which reports need to send in Report group 3
        103_4: 0

# TPS412 Touch Panel Switch 2 Channel
# https://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/429
-   deviceName: TPS412 Touch Panel Switch 2 Channel
    manufacturerId: 351
    productTypeId: 16673
    groups:
        1: 1
        2: 1
        3: 1

-   deviceName: BeNext Panic Watch
    manufacturerId: 138
    productTypeId: 21
    groups:
        1: 1
    config:
        4_1: 0        

-   deviceName: Fibaro Relais FGS-212
    manufacturerId: 271
    productTypeId: 1026
    groups:
        3: 1

# Fibargroup FGSD002 Smoke Detector
# https://manuals.fibaro.com/de/smoke-sensor/
# https://www.opensmarthouse.org/zwavedatabase/878
-   deviceName: Fibargroup FGSD002 Smoke Detector
    manufacturerId: 271 #0x010F
    productTypeId: 3074 #0x0C02
    config:
        20_2: 0 # Temperature report interval - 0: reports inactive - default: 1 = 10 seconds
    wakeup: 65535 # max value, a little more than 18 hours. 0 would disable wakeup completely - default was 6 hours

# Fibargroup FGPB101 The Button
# https://manuals.fibaro.com/de/button/
# https://www.opensmarthouse.org/zwavedatabase/436
-   deviceName: Fibargroup FGPB101 The Button
    manufacturerId: 271 #0x010F
    productTypeId: 3841 #0x0F01
    groups:
        1: 1 # “Lifeline” reports the device status and allows for assigning single device only (main controller by default).
        2: 1 # “On/Off” is assigned to clicking the button
    config:
        1_1: 0 # Scenes sent to the controller (127=all, default) (additive bit field)
        10_1: 1 # Key Pressed 1 time – command sent to 2nd association group ( 1: SWITCH On)
        11_2: 255 # Key Pressed 1 time – value of SWITCH ON command sent to 2nd association group
        12_1: 1 # Key Pressed 2 times – command sent to 2nd association group ( 1: SWITCH On)
        13_2: 255 # Key Pressed 2 time – value of SWITCH ON command sent to 2nd association group
        14_1: 1 # Key Pressed 3 times – command sent to 2nd association group ( 1: SWITCH On)
        15_2: 255 # Key Pressed 3 time – value of SWITCH ON command sent to 2nd association group
    wakeup: 64800 # max value, 18 hours. default=0 would disable wakeup completely

# AEON Labs ZW117 Range Extender 6
# https://www.opensmarthouse.org/zwavedatabase/527
-   deviceName: AEON Labs ZW117 Range Extender 6
    manufacturerId: 134 #(0x86)
    productTypeId: 4 # (0x4)
    productId: 117 # (0x0075)